# Generated by Django 2.1.4 on 2019-06-26 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Definicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_horas', models.IntegerField()),
                ('fecha', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Minuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('asistentes', models.ManyToManyField(to='minuta.Asistente')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.FloatField()),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('C', 'Cobro'), ('P', 'Pago')], default='C', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Programador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('es_socio', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('horas', models.IntegerField()),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='minuta.Empresa')),
                ('programadores', models.ManyToManyField(to='minuta.Programador')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='minuta.Programador')),
            ],
        ),
        migrations.CreateModel(
            name='Responsabilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.TextField()),
                ('fecha', models.DateField(blank=True, null=True)),
                ('minuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsabilidades', to='minuta.Minuta')),
                ('responsables', models.ManyToManyField(to='minuta.Asistente')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('minuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='minuta.Minuta')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('C', 'Critical'), ('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='M', max_length=1)),
                ('status', models.CharField(choices=[('A', 'Abierto'), ('P', 'En progreso'), ('B', 'Bloqueado'), ('R', 'Resuelto'), ('C', 'Cerrado')], default='A', max_length=1)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='minuta.Proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='movimiento',
            name='programador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='minuta.Programador'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='minuta.Proyecto'),
        ),
        migrations.AddField(
            model_name='minuta',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minutas', to='minuta.Proyecto'),
        ),
        migrations.AddField(
            model_name='hora',
            name='programador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_aplicadas', to='minuta.Programador'),
        ),
        migrations.AddField(
            model_name='hora',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_aplicadas', to='minuta.Proyecto'),
        ),
        migrations.AddField(
            model_name='hora',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_aplicadas', to='minuta.Ticket'),
        ),
        migrations.AddField(
            model_name='definicion',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definiciones', to='minuta.Tema'),
        ),
        migrations.AddField(
            model_name='asistente',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='minuta.Empresa'),
        ),
    ]
