# Generated by Django 2.1.4 on 2019-06-26 20:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minuta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='nombre',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_apertura',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_estimada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='prioridad',
            field=models.CharField(choices=[('C', 'Critico'), ('A', 'Alto'), ('M', 'Medio'), ('B', 'Bajo')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'En progreso'), ('B', 'Bloqueado'), ('R', 'Resuelto'), ('C', 'Cerrado')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='minuta.Ticket'),
        ),
    ]
