# Generated by Django 2.1.4 on 2018-12-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minuta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistente',
            name='apellido',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minuta',
            name='motivo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
