# Generated by Django 2.1.4 on 2019-06-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minuta', '0002_auto_20190626_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tipo',
            field=models.CharField(choices=[('A', 'Agregado'), ('M', 'Modificacion'), ('E', 'Error'), ('O', 'Otro')], default='O', max_length=1),
        ),
    ]
