# Generated by Django 2.1.4 on 2018-12-09 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minuta', '0002_auto_20181209_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistente',
            name='minuta',
        ),
        migrations.AddField(
            model_name='asistente',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minuta.Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minuta',
            name='asistentes',
            field=models.ManyToManyField(to='minuta.Asistente'),
        ),
    ]
