# Generated by Django 2.1.4 on 2019-01-15 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minuta', '0007_auto_20190110_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Programador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horas',
            name='programador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas', to='minuta.Programador'),
        ),
        migrations.AddField(
            model_name='horas',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas', to='minuta.Proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='programadores',
            field=models.ManyToManyField(to='minuta.Programador'),
        ),
    ]
