# Generated by Django 2.1.4 on 2019-01-15 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minuta', '0008_auto_20190115_2318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Horas',
            new_name='Hora',
        ),
    ]
