# Generated by Django 2.1.4 on 2019-01-15 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minuta', '0009_auto_20190115_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('programador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='minuta.Programador')),
            ],
        ),
    ]
