# Generated by Django 2.1.4 on 2019-01-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minuta', '0012_programador_es_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
